@echo off
fd_test 0.raw
fd_test 1.raw
fd_test 10.raw
fd_test 11.raw
fd_test 13.raw
fd_test 14.raw
fd_test 2.raw
fd_test 3.raw
fd_test 4.raw
fd_test 5.raw
fd_test 7.raw
fd_test 8.raw
fd_test 9.raw
fd_test grad.raw
fd_test tank.raw
fd_test voice.raw
fd_test voice2.raw
